### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ahaerpfer** [ahaerpfer/ansible-inventory-omd-livestatus#6]
The code runs only under Python 2 at the moment. Main issue: proper string handling (Unicode vs bytes), e.g.:

```
$ ./omd_livestatus.py --static --ssh nagios.example.com
Traceback (most recent call last):
  File "./omd_livestatus.py", line 286, in <module>
    by_ip=opts.by_ip)
  File "./omd_livestatus.py", line 82, in __init__
    self.load_from_omd()
  File "./omd_livestatus.py", line 96, in load_from_omd
    answer = self._read_from_ssh()
  File "./omd_livestatus.py", line 136, in _read_from_ssh
    out, err = p.communicate(input=OMDLivestatusInventory._def_host_query)
  File "/Users/xx/anaconda/lib/python3.5/subprocess.py", line 1068, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Users/xx/anaconda/lib/python3.5/subprocess.py", line 1687, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
```

**Comment by ahaerpfer** [comment]
Fixed by properly encoding/decoding all the stuff that goes in and out via the network.
